### ISSUE TITLE
add unit_of_measurement and device_class

### ISSUE THREAD

**Issue by milandzuris** [mrk-its/homeassistant-blitzortung#101]
Hi, please add this to Code

```
sensor.lightning_azimuth:
  unit_of_measurement: °
sensor.lightning_distance:
  device_class: distance
```
