### ISSUE TITLE
per device source

### ISSUE THREAD

**Issue by 532910** [mrk-its/homeassistant-blitzortung#144]
I have multiple blitzortung "devices" and would like to show them on different map widgets.
Please add support to configure source attribute for blitzortung devices, or add device name source attribute to to make them different.

**Comment by bieniu** [comment]
If you don't explain exactly what your feature request is about, you might be waiting forever.
Devices (or rather, services in that case) don't have attributes. Are you referring to entities? If so, which entities?
Why is the entity name not sufficient for you?

**Comment by bieniu** [comment]
Much better, now I understand what you mean.

It's quite simple to implement, but...
- no other `geo_location` integration does this
- this will make all Blitzortung config entries visible under the same name in the map editor

  <img width="287" height="251" alt="Image" src="https://github.com/user-attachments/assets/24a56a14-e588-41fb-8e50-17896309e6c1" />

- that change would be a breaking change

For the reasons above, I wouldn't want to implement such a change. Home Assistant core simply doesn't provide such a capability at this time.

But... I think you should achieve what you need by adding a zone in the place where you want to track lightning.

For example, you add a zone with the coordinates you use in the Blitozrtung integration config entry, let's call this zone Zone 1. And you configure the card like this:

```yaml
type: map
entities:
  - entity: zone.zone_1
geo_location_sources:
  - source: blitzortung
    focus: false
```

Unfortunately, there's always a catch 😉 There seems to be a bug in the Map card and it doesn't show the map of the zone surroundings other than Home. I've opened an issue in the frontend repository https://github.com/home-assistant/frontend/issues/29902

**Comment by bieniu** [comment]
I didn't notice the `fit_zones` option in the documentation. With `fit_zones: true` the card correctly displays the map around the zone.

```yaml
type: map
fit_zones: true
entities:
  - entity: zone.zone_1
geo_location_sources:
  - source: blitzortung
    focus: false
```

> could you name other geolocation providers that you meant?

https://www.home-assistant.io/integrations/?cat=geolocation
