### ISSUE TITLE
Geolocation events: which source should I use to filter these on the map card?

### ISSUE THREAD

**Issue by groenmarsmannetje** [mrk-its/homeassistant-blitzortung#25]
I would like to show a [Lovelace map card](https://www.home-assistant.io/lovelace/map/) with the lighting strikes, but to me it is not clear which "geo_location_source" I should use to only display these Blitzortung locations on the map. Please explain.

**Comment by MrSuttonmann** [comment]
I'm not the author of the software, but I think [this line](https://github.com/mrk-its/homeassistant-blitzortung/blob/658d9e2c5b0369bb1526311b016870945b7c7984/custom_components/blitzortung/geo_location.py#L33) of `geo_location.py` is key:

```
coordinator = hass.data[DOMAIN][config_entry.entry_id]
```

I think the const `DOMAIN` is the geolocation source id, [which in this case is set to `blitzortung` in `const.py`.](https://github.com/mrk-its/homeassistant-blitzortung/blob/658d9e2c5b0369bb1526311b016870945b7c7984/custom_components/blitzortung/const.py#L5)

I'm setting my own map to that to see what happens, but I'm not 100% confident that is the correct value.

![image](https://user-images.githubusercontent.com/7480500/115572545-e8009800-a2b7-11eb-8880-a5d1009549d3.png)

**Comment by groenmarsmannetje** [comment]
I have also set it up like that... now have to wait for some thunder storms ;-)

**Comment by DavidFW1960** [comment]
I don't think that will work as the integration provides a distance, azimuth and number of strikes.
![image](https://user-images.githubusercontent.com/36390762/117396329-0f549780-af3d-11eb-874b-caefecd08d67.png)
I have been through this some time ago with this on the forum.
You have to make an automation that creates a device tracker from it:
```
  - id: 'lightning'
    alias: Lightning
    trigger:
    - platform: state
      entity_id: sensor.blitzortung_lightning_azimuth
    condition: 
    - "{{ states('sensor.blitzortung_lightning_counter') | float != 0 }}"
    mode: restart
    action:
    - service: device_tracker.see
      data:
        dev_id: lightning
        gps:
          - "{{ state_attr('sensor.blitzortung_lightning_azimuth', 'lat') }}"
          - "{{ state_attr('sensor.blitzortung_lightning_azimuth', 'lon') }}"
```
It will then make a device_tracker in known_devices.yaml or you might need to manually create it..
```
lightning:
  icon:
  mac:
  name: lightning
  picture:
  track: true
```
Then you can add to a map card in Lovelace like this:
```
          - type: map
            show_header_toggle: false
            dark_mode: true
            geo_location_sources:       #these and the sources are optional
              - nsw_rural_fire_service_feed
              - gdacs
            entities:
              - zone.home
              - device_tracker.lightning
```
Note when there is lightning, it will create a geo_location.lightning* entity but you can't plot it without calling the device.see service...
I am actually wondering what will happen here when they finally do kill off known_devices.yaml? @mrk-its
