### ISSUE TITLE
Lightning Count toggles briefly to unknown at GMT 0:00 (midnight)

### ISSUE THREAD

**Issue by StormyKnight17** [mrk-its/homeassistant-blitzortung#55]
![Clipboard01](https://user-images.githubusercontent.com/99853895/171521623-bc25196e-ee64-4fca-a06b-3ecdeed3db8d.jpg)

Note my Timezone is +10 so 10am is UTC Midnight for me.

I found this by using an automation trigger for the counter of From: 0 To: (BLANK)
The idea was to trigger on change from 0 to any other number, but it seems that it goes to 'unknown' at this time of day each day. It doesn't do it at any other time.

Can anyone else confirm this is happening for them?

I have an automation that advises me on any change of the counter value for testing. It is triggering each day at UTC 0:00

```
alias: TEMP - Lightning Counter Monitor
description: ''
trigger:
  - platform: state
    entity_id:
      - sensor.blitzortung_lightning_counter
condition:
  - condition: not
    conditions:
      - condition: numeric_state
        entity_id: sensor.blitzortung_lightning_counter
        above: '0'
action:
  - service: notify.mobile_app_iphone
    data_template:
      message: |
        {{states('sensor.blitzortung_lightning_counter')}} 
      title: Lightning Count Change In Value
mode: single
```
