### ISSUE TITLE
Enhancement Idea: Allow map card

### ISSUE THREAD

**Issue by Node815** [mrk-its/homeassistant-blitzortung#78]
During an active storm, I like to watch to see where all of the strikes are and go to the built in Home Assistant Map.  But that also shows my list of places/pins I've dropped for geolocation such as stores and other places.  

I would like to know if there is a way I could set up a map card to only show the (LS) Strikes only?  I didn't see an entity to show except where the previous ones were individually and not a group.   In other words, on the same page as the strikes and distance, I would like to include a map showing my user defined radius where all of the strikes are without all of the other saved locations.   Is this possible?

**Comment by phillprice** [comment]
It's not listed as a source in the UI but this still works:
```
      - type: conditional
        conditions:
          - entity: sensor.blitzortung_lightning_counter
            state_not: '0'
        card:
          type: map
          entities:
            - entity: zone.home
          geo_location_sources:
            - blitzortung
          dark_mode: false
          default_zoom: 10
          aspect_ratio: '80%'
          auto_fit: true
```
