### ISSUE TITLE
lightning-detector-card support

### ISSUE THREAD

**Issue by Norien** [mrk-its/homeassistant-blitzortung#9]
I'm struggling to find a meaningful way to display this in my dashboard. I did come across this in hacs and it looks perfect. Is there any way to get this working together?

https://github.com/ironsheep/lovelace-lightning-detector-card

Thanks for all you do!!

**Comment by mrk-its** [comment]
This widget looks great, but it is able to only show distance. Blitzortung provides lat/lon coordinates of lightning, it would be great to show it on map, like: https://map.blitzortung.org/#3.76/48.41/15.98
I already did some successful experiments with custom map widget, stay tuned!

**Comment by sgofferj** [comment]
And there I was just about to open a feature request to display lightnings on the HA map... :smile: 
The now defunct WWLLN integration displayed the lightnings on the HA map which was kinda nice...
There is a canvas-gauge-card for HA with which one could make a relatively nice indicator for the azimuth. That's on my list.
@mrk-its Could we have a "detected" entity, which goes from "" to something like "detected" and back to "" whenever a strike within the interest zone was detected

**Comment by mrk-its** [comment]
@sgofferj I'll check how WWLLN was integrated with HA map, thanks!
Regarding this "detected" entity - you can easily achieve such things with template sensor, like:
```
sensor:
  - platform: template
    sensors:
      is_storm_detected:
        value_template: '{{ states("sensor.blitzortung_lightning_distance") != "unknown" }}'```

**Comment by sgofferj** [comment]
Successfully made a [canvas-gauge-card](https://github.com/custom-cards/canvas-gauge-card) for the strike direction:

![Screenshot_20200804_005621](https://user-images.githubusercontent.com/3258466/89231177-77accc00-d5ed-11ea-9362-b9a4bd436fe8.png)

```
card_height: 220
entity: sensor.blitzortung_lightning_azimuth
font_size: 1em
gauge:
  borderInnerWidth: 0
  borderMiddleWidth: 0
  borderOuterWidth: 0
  borderShadowWidth: 0
  borders: false
  height: 220
  highlights: []
  majorTicks:
    - 'N'
    - E
    - S
    - W
    - ''
  maxValue: 360
  minValue: 0
  minorTicks: 2
  startAngle: 180
  strokeTicks: true
  ticksAngle: 360
  type: radial-gauge
  valueBox: false
  width: 220
shadow_height: 12%
type: 'custom:canvas-gauge-card'
```

@mrk-its That works of course. I was more thinking of an entity that triggers for every single lightning to make a sound or flash a light :smiley: But that probably also can be done with some template trickery.
